export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET = 'AUTH_RESET';

export const NEW_POST_START = 'NEW_POST_START';
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS';
export const NEW_POST_FAIL = 'NEW_POST_FAIL';

export const UPDATE_CODE = 'UPDATE_CODE';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FULL_POST_START = 'FULL_POST_START';
export const FULL_POST_SUCCESS = 'FULL_POST_SUCCESS';
export const FULL_POST_FAIL = 'FULL_POST_FAIL';

export const RESPONSE_START = 'RESPONSE_START';
export const RESPONSE_SUCCESS = 'RESPONSE_SUCCESS';
export const RESPONSE_FAIL = 'RESPONSE_FAIL';

export const DELETE_RESPONSE_START = 'DELETE_RESPONSE_START';
export const DELETE_RESPONSE_SUCCESS = 'DELETE_RESPONSE_SUCCESS';
export const DELETE_RESPONSE_FAIL = 'DELETE_RESPONSE_FAIL';

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';